# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OnlineMusicDownloader.ui'
#
# Created: Mon Dec 19 00:27:40 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(780, 450)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OnlineMusicDownloader", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 13, 751, 361))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.AllWidget = QtGui.QVBoxLayout(self.layoutWidget)
        self.AllWidget.setMargin(0)
        self.AllWidget.setObjectName(_fromUtf8("AllWidget"))
        self.ServicesURLsInput = QtGui.QVBoxLayout()
        self.ServicesURLsInput.setObjectName(_fromUtf8("ServicesURLsInput"))
        self.ServicesURLsLabel = QtGui.QLabel(self.layoutWidget)
        self.ServicesURLsLabel.setText(QtGui.QApplication.translate("MainWindow", "Services URL(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.ServicesURLsLabel.setObjectName(_fromUtf8("ServicesURLsLabel"))
        self.ServicesURLsInput.addWidget(self.ServicesURLsLabel)
        self.ServicesURL = QtGui.QTextEdit(self.layoutWidget)
        self.ServicesURL.setObjectName(_fromUtf8("ServicesURL"))
        self.ServicesURLsInput.addWidget(self.ServicesURL)
        self.AllWidget.addLayout(self.ServicesURLsInput)
        self.SaveWidget = QtGui.QHBoxLayout()
        self.SaveWidget.setObjectName(_fromUtf8("SaveWidget"))
        self.SavefileLabel = QtGui.QLabel(self.layoutWidget)
        self.SavefileLabel.setText(QtGui.QApplication.translate("MainWindow", "Save file to", None, QtGui.QApplication.UnicodeUTF8))
        self.SavefileLabel.setObjectName(_fromUtf8("SavefileLabel"))
        self.SaveWidget.addWidget(self.SavefileLabel)
        self.DownloadFolderInput = QtGui.QLineEdit(self.layoutWidget)
        self.DownloadFolderInput.setObjectName(_fromUtf8("DownloadFolderInput"))
        self.SaveWidget.addWidget(self.DownloadFolderInput)
        self.BrowseButton = QtGui.QPushButton(self.layoutWidget)
        self.BrowseButton.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseButton.setObjectName(_fromUtf8("BrowseButton"))
        self.SaveWidget.addWidget(self.BrowseButton)
        self.AllWidget.addLayout(self.SaveWidget)
        self.DownloadWidget = QtGui.QHBoxLayout()
        self.DownloadWidget.setObjectName(_fromUtf8("DownloadWidget"))
        self.DownloadAcceleratorLabel = QtGui.QLabel(self.layoutWidget)
        self.DownloadAcceleratorLabel.setText(QtGui.QApplication.translate("MainWindow", "Download Accelerator", None, QtGui.QApplication.UnicodeUTF8))
        self.DownloadAcceleratorLabel.setObjectName(_fromUtf8("DownloadAcceleratorLabel"))
        self.DownloadWidget.addWidget(self.DownloadAcceleratorLabel)
        self.PythonUrllibRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.PythonUrllibRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Python urlibretrieve", None, QtGui.QApplication.UnicodeUTF8))
        self.PythonUrllibRadioButton.setObjectName(_fromUtf8("PythonUrllibRadioButton"))
        self.DownloadWidget.addWidget(self.PythonUrllibRadioButton)
        self.PythoncURLRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.PythoncURLRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Python cURL", None, QtGui.QApplication.UnicodeUTF8))
        self.PythoncURLRadioButton.setObjectName(_fromUtf8("PythoncURLRadioButton"))
        self.DownloadWidget.addWidget(self.PythoncURLRadioButton)
        self.WgetRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.WgetRadioButton.setText(QtGui.QApplication.translate("MainWindow", "GNU wget", None, QtGui.QApplication.UnicodeUTF8))
        self.WgetRadioButton.setObjectName(_fromUtf8("WgetRadioButton"))
        self.DownloadWidget.addWidget(self.WgetRadioButton)
        self.DownloadButton = QtGui.QPushButton(self.layoutWidget)
        self.DownloadButton.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.DownloadButton.setObjectName(_fromUtf8("DownloadButton"))
        self.DownloadWidget.addWidget(self.DownloadButton)
        self.SaveLinksButton = QtGui.QPushButton(self.layoutWidget)
        self.SaveLinksButton.setText(QtGui.QApplication.translate("MainWindow", "Save links to text file", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveLinksButton.setObjectName(_fromUtf8("SaveLinksButton"))
        self.DownloadWidget.addWidget(self.SaveLinksButton)
        self.AllWidget.addLayout(self.DownloadWidget)
        self.LastGroup = QtGui.QHBoxLayout()
        self.LastGroup.setObjectName(_fromUtf8("LastGroup"))
        self.WorkingStatusGroup = QtGui.QHBoxLayout()
        self.WorkingStatusGroup.setObjectName(_fromUtf8("WorkingStatusGroup"))
        self.WorkingStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.WorkingStatusLabel.setText(QtGui.QApplication.translate("MainWindow", "Working Status :", None, QtGui.QApplication.UnicodeUTF8))
        self.WorkingStatusLabel.setObjectName(_fromUtf8("WorkingStatusLabel"))
        self.WorkingStatusGroup.addWidget(self.WorkingStatusLabel)
        self.WorkingStatus = QtGui.QLineEdit(self.layoutWidget)
        self.WorkingStatus.setEnabled(False)
        self.WorkingStatus.setObjectName(_fromUtf8("WorkingStatus"))
        self.WorkingStatusGroup.addWidget(self.WorkingStatus)
        self.LastGroup.addLayout(self.WorkingStatusGroup)
        self.StopClose = QtGui.QHBoxLayout()
        self.StopClose.setObjectName(_fromUtf8("StopClose"))
        self.StopDownloadButton = QtGui.QPushButton(self.layoutWidget)
        self.StopDownloadButton.setText(QtGui.QApplication.translate("MainWindow", "Stop Download", None, QtGui.QApplication.UnicodeUTF8))
        self.StopDownloadButton.setObjectName(_fromUtf8("StopDownloadButton"))
        self.StopClose.addWidget(self.StopDownloadButton)
        self.CloseButton = QtGui.QPushButton(self.layoutWidget)
        self.CloseButton.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.StopClose.addWidget(self.CloseButton)
        self.LastGroup.addLayout(self.StopClose)
        self.AllWidget.addLayout(self.LastGroup)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.ServicesURLsLabel.setBuddy(self.ServicesURL)
        self.SavefileLabel.setBuddy(self.DownloadFolderInput)
        self.DownloadAcceleratorLabel.setBuddy(self.PythonUrllibRadioButton)
        self.WorkingStatusLabel.setBuddy(self.WorkingStatus)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.CloseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ServicesURL, self.DownloadFolderInput)
        MainWindow.setTabOrder(self.DownloadFolderInput, self.BrowseButton)
        MainWindow.setTabOrder(self.BrowseButton, self.PythonUrllibRadioButton)
        MainWindow.setTabOrder(self.PythonUrllibRadioButton, self.PythoncURLRadioButton)
        MainWindow.setTabOrder(self.PythoncURLRadioButton, self.WgetRadioButton)
        MainWindow.setTabOrder(self.WgetRadioButton, self.DownloadButton)
        MainWindow.setTabOrder(self.DownloadButton, self.SaveLinksButton)
        MainWindow.setTabOrder(self.SaveLinksButton, self.WorkingStatus)
        MainWindow.setTabOrder(self.WorkingStatus, self.StopDownloadButton)
        MainWindow.setTabOrder(self.StopDownloadButton, self.CloseButton)

    def retranslateUi(self, MainWindow):
        pass

